# Generated by Django 4.2.7 on 2023-12-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0004_alter_deposit_user_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=20, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=20, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
