# Generated by Django 4.2.7 on 2023-12-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invest", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
